#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 The Worx Company
# Author: Kurt Vanderwater <kurt@worxco.net>

# ============================================================
# migration/scripts/jumpbox/dump-codebase.sh
#
# Purpose:  Tar the client's Drupal codebase on the prod app server
#           (React2) and stream the archive directly to the sandbox S3
#           migration bucket. Excludes settings.php, files/, private/,
#           .git, .ddev, and services.yml so the sandbox doesn't get
#           polluted with prod-specific config or user uploads.
#
# Flow (six phases):
#   1. Preconditions       (root, tools, SSH key, AWS creds)
#   2. Test SSH            (jumpbox → React2 as ubuntu)
#   3. Source metadata     (approximate total size on React2)
#   4. Confirmation        (honors CONFIRMED=yes)
#   5. Stream tar → S3     (ssh "tar cz" | aws s3 cp -)
#   6. Verify S3 upload
#
# Idempotent: yes — S3 PUT is atomic and overwrites the previous
#   object; there's no local intermediate on the jumpbox.
#
# Environment variables (all optional, listed with defaults):
#   MIGRATION_BUCKET   Sandbox S3 bucket        (sandbox-migration-kv-worxco)
#   DUMP_S3_KEY        Target object key         (dumps/drupal-codebase.tar.gz)
#   SOURCE_HOST        React2 IP or hostname     (172.31.23.46)
#   SOURCE_USER        SSH user on React2        (ubuntu)
#   DRUPAL_ROOT        Codebase root on React2   (/var/www/html/zoning_info_platform)
#   SSH_KEY            SSH private key location  (/root/.ssh/id_ed25519)
#   CONFIRMED          yes = skip Y/N confirmation
#   DRY_RUN            yes = preview commands without executing
#
# Runs as:  root on the jumpbox. The SSH key at /root/.ssh/id_ed25519
#           was generated by `make jumpbox-pubkey`; its pubkey must be
#           in React2's ubuntu@authorized_keys.
# Host:     Prod jumpbox (EC2 in vpc-7fbd291a, prod account 978068244875)
# Called by:
#   - Directly (in an SSM interactive session, `sudo ./dump-codebase.sh`)
#   - By a future `make dump-codebase` Makefile target that pushes this
#     script to jumpbox via S3 and executes via `aws ssm send-command`
#
# Logging:  Written to /var/log/worxco-migration/dump-codebase-<UTC>.log
#           and uploaded to s3://$MIGRATION_BUCKET/logs/YYYY-MM-DD/ on exit.
#
# Created:  2026-07-13
# ============================================================

set -euo pipefail

# Source shared helpers (colors, log_init, confirm_or_exit, ...)
source "$(dirname "$(readlink -f "$0")")/../_common.sh"

# ============================================================
# Configuration defaults (all overridable by environment)
# ============================================================
MIGRATION_BUCKET="${MIGRATION_BUCKET:-sandbox-migration-kv-worxco}"
DUMP_S3_KEY="${DUMP_S3_KEY:-dumps/drupal-codebase.tar.gz}"
SOURCE_HOST="${SOURCE_HOST:-172.31.23.46}"
SOURCE_USER="${SOURCE_USER:-ubuntu}"
DRUPAL_ROOT="${DRUPAL_ROOT:-/var/www/html/zoning_info_platform}"
SSH_KEY="${SSH_KEY:-/root/.ssh/id_ed25519}"

# Codebase-specific exclusions — anything NOT in the sandbox copy.
# Paths are relative to DRUPAL_ROOT (matches tar's `-C` semantics).
EXCLUDES=(
  './web/sites/default/settings.php'
  './web/sites/default/settings.local.php'
  './web/sites/default/services.yml'
  './web/sites/default/files'
  './private'
  './.git'
  './.ddev'
)

# ============================================================
# Set up logging + on-exit S3 upload of the log file
# ============================================================
log_init "dump-codebase"
trap 'log_upload_and_exit "$MIGRATION_BUCKET"' EXIT

log_step "dump-codebase — React2 Drupal codebase → sandbox S3"
log_info "MIGRATION_BUCKET = $MIGRATION_BUCKET"
log_info "DUMP_S3_KEY      = $DUMP_S3_KEY"
log_info "SOURCE_HOST      = $SOURCE_HOST"
log_info "SOURCE_USER      = $SOURCE_USER"
log_info "DRUPAL_ROOT      = $DRUPAL_ROOT"
log_info "SSH_KEY          = $SSH_KEY"
log_info "Excluded paths (relative to DRUPAL_ROOT):"
for excl in "${EXCLUDES[@]}"; do
  log_info "  - $excl"
done
if [ "${DRY_RUN:-}" = "yes" ]; then
  log_warn "DRY_RUN=yes — commands will be previewed, not executed"
fi

# ============================================================
# Phase 1 of 6: Preconditions
# ============================================================
log_step "Phase 1/6: Preconditions"

if [ "$(id -u)" -ne 0 ]; then
  log_error "Must run as root — the SSH key at $SSH_KEY belongs to root."
  log_error "Example: sudo -E ./dump-codebase.sh"
  exit 1
fi

require_env MIGRATION_BUCKET DUMP_S3_KEY SOURCE_HOST SOURCE_USER DRUPAL_ROOT SSH_KEY

for tool in ssh tar aws; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    log_error "Required tool '$tool' not found on PATH."
    exit 1
  fi
done

if [ ! -f "$SSH_KEY" ]; then
  log_error "SSH private key not found at $SSH_KEY"
  log_error "From your Mac or deploy-host, run:"
  log_error "  cd migration && make jumpbox-pubkey"
  log_error "That creates + displays the pubkey; add it to React2's authorized_keys."
  exit 1
fi

if ! aws sts get-caller-identity --query Account --output text >/dev/null 2>&1; then
  log_error "AWS credentials are not working. Check instance role attachment."
  exit 1
fi

log_ok "Preconditions satisfied"

# ============================================================
# Phase 2 of 6: Test SSH connectivity to React2
# ============================================================
log_step "Phase 2/6: Test SSH to $SOURCE_USER@$SOURCE_HOST"

# StrictHostKeyChecking=accept-new: silently trust the host key on first
# connect (safe: React2 is prod-known and inside our own account). Prevents
# an interactive prompt when the script runs non-interactively via SSM.
# BatchMode=yes: no interactive password prompts — key auth or bust.
if ! ssh -i "$SSH_KEY" \
      -o StrictHostKeyChecking=accept-new \
      -o ConnectTimeout=10 \
      -o BatchMode=yes \
      "$SOURCE_USER@$SOURCE_HOST" "hostname; whoami" >/dev/null 2>&1; then
  log_error "Cannot SSH to $SOURCE_USER@$SOURCE_HOST"
  log_error "Check:"
  log_error "  1) jumpbox pubkey is in React2's ~$SOURCE_USER/.ssh/authorized_keys"
  log_error "  2) network path from jumpbox to React2 (same VPC region)"
  log_error "  3) React2's SG allows SSH from the jumpbox's subnet"
  exit 1
fi

REMOTE_HOSTNAME=$(ssh -i "$SSH_KEY" -o BatchMode=yes "$SOURCE_USER@$SOURCE_HOST" hostname)
log_ok "SSH working — connected to $REMOTE_HOSTNAME as $SOURCE_USER"

# ============================================================
# Phase 3 of 6: Fetch source metadata
# ============================================================
log_step "Phase 3/6: Fetch source metadata"

# du -sb needs sudo since some paths under DRUPAL_ROOT may be www-data
# owned or root-owned. Passwordless sudo is standard on Ubuntu AMIs.
TOTAL_SIZE=$(ssh -i "$SSH_KEY" -o BatchMode=yes "$SOURCE_USER@$SOURCE_HOST" \
  "sudo du -sb '$DRUPAL_ROOT' 2>/dev/null | cut -f1" || echo "0")

if [ "$TOTAL_SIZE" = "0" ] || [ -z "$TOTAL_SIZE" ]; then
  log_warn "Could not measure source size (permissions? path?). Proceeding anyway."
  TOTAL_MB=0
else
  TOTAL_MB=$(( TOTAL_SIZE / 1024 / 1024 ))
  log_info "Source $DRUPAL_ROOT total size: ~${TOTAL_MB} MB (before exclusions)"
  log_info "Expect the tar.gz to be a fraction of this — excludes remove files/,"
  log_info "and gzip compresses text (code/config) well."
fi

# ============================================================
# Phase 4 of 6: Confirmation
# ============================================================
log_step "Phase 4/6: Confirmation"

confirm_or_exit "About to tar the Drupal codebase on React2 and stream to sandbox S3.
    Source: $SOURCE_USER@$SOURCE_HOST:$DRUPAL_ROOT (~${TOTAL_MB} MB pre-exclude)
    Target: s3://$MIGRATION_BUCKET/$DUMP_S3_KEY
    Excludes: settings*.php, services.yml, files/, private/, .git, .ddev
    Impact: sustained read I/O on React2's disk for the tar duration
    (usually a few minutes; less impact than the DB dump)."

# ============================================================
# Phase 5 of 6: Stream tar over SSH → S3
# ============================================================
log_step "Phase 5/6: tar over SSH → S3 stream"

# Build tar's --exclude args from the EXCLUDES array
EXCLUDE_ARGS=""
for excl in "${EXCLUDES[@]}"; do
  EXCLUDE_ARGS="$EXCLUDE_ARGS --exclude=$excl"
done

log_info "Starting tar stream from React2 → sandbox S3"
log_info "(pipeline: React2 tar → SSH → jumpbox → aws s3 cp -)"

if is_dry_run; then
  log_info "[DRY_RUN] would run:"
  log_info "  ssh $SOURCE_USER@$SOURCE_HOST \\"
  log_info "    \"sudo tar czf - -C '$DRUPAL_ROOT' $EXCLUDE_ARGS .\" \\"
  log_info "    | aws s3 cp - s3://$MIGRATION_BUCKET/$DUMP_S3_KEY"
else
  time_start=$SECONDS

  # `set -o pipefail` is on (from `set -euo pipefail`), so the pipeline
  # exits non-zero if any component fails. We wrap in `if !` to catch it
  # and remove any truncated S3 object.
  if ! ssh -i "$SSH_KEY" -o BatchMode=yes "$SOURCE_USER@$SOURCE_HOST" \
        "sudo tar czf - -C '$DRUPAL_ROOT' $EXCLUDE_ARGS ." \
      | aws s3 cp - "s3://$MIGRATION_BUCKET/$DUMP_S3_KEY"
  then
    log_error "Tar/upload pipeline failed. Removing partial S3 object..."
    aws s3 rm "s3://$MIGRATION_BUCKET/$DUMP_S3_KEY" 2>/dev/null || true
    exit 1
  fi

  time_elapsed=$(( SECONDS - time_start ))
  log_ok "Tar stream completed in ${time_elapsed}s"
fi

# ============================================================
# Phase 6 of 6: Verify S3 upload
# ============================================================
log_step "Phase 6/6: Verify S3 upload"

if is_dry_run; then
  log_info "[DRY_RUN] would run: aws s3api head-object ..."
else
  S3_SIZE=$(aws s3api head-object \
      --bucket "$MIGRATION_BUCKET" --key "$DUMP_S3_KEY" \
      --query ContentLength --output text 2>/dev/null || echo "0")

  if [ "$S3_SIZE" = "0" ] || [ -z "$S3_SIZE" ]; then
    log_error "S3 object does not exist or head-object failed."
    exit 1
  fi

  # A Drupal codebase tarball should be at least a few MB (composer's
  # vendor/ alone is dozens of MB). Sub-1MB likely means a broken pipe.
  if [ "$S3_SIZE" -lt 1048576 ]; then
    log_error "S3 object is only $S3_SIZE bytes — suspiciously small."
    log_error "Investigate before running restore-codebase on the sandbox side."
    exit 1
  fi

  S3_MB=$(( S3_SIZE / 1024 / 1024 ))
  if [ "$TOTAL_MB" -gt 0 ]; then
    RATIO=$(( S3_MB * 100 / TOTAL_MB ))
    log_ok "S3 object: ${S3_MB} MB at s3://$MIGRATION_BUCKET/$DUMP_S3_KEY"
    log_info "Compression + exclusion: ${S3_MB} MB / ${TOTAL_MB} MB ≈ ${RATIO}% of source"
  else
    log_ok "S3 object: ${S3_MB} MB at s3://$MIGRATION_BUCKET/$DUMP_S3_KEY"
  fi
fi

# ============================================================
# Done
# ============================================================
if is_dry_run; then
  log_step "dump-codebase — DRY RUN complete (no upload performed)"
  log_info "Would have uploaded to s3://$MIGRATION_BUCKET/$DUMP_S3_KEY"
  log_info "Re-run without DRY_RUN=yes to perform the actual tar+upload."
else
  log_step "dump-codebase complete"
  log_ok "Codebase tarball uploaded to s3://$MIGRATION_BUCKET/$DUMP_S3_KEY"
  log_info "Next: on deploy-host, run 'cd migration && make restore-codebase'"
fi

# License: GPL-2.0-or-later
# Copyright (C) 2026 The Worx Company
# Author: Kurt Vanderwater <kurt@worxco.net>
